version: '3'

services: 
  
  api:
    build:
      context: .
      dockerfile: Dockerfile   
    links:     
      
    volumes:
      - /app/node_modules
      - .:/app 
    environment:
      - PORT=8000
    ports:
      - "3000:8000"
  
  
  
  
  
    
    